name: Dependency Review

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency-review
    runs-on: ubuntu-latest
    # actions/dependency-review-action requires GitHub Dependency Graph to be enabled for the repository.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
